In [1]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Define your categorical data
job_titles = ['Engineer', 'Designer', 'Manager', 'Technician', 'Manager', 'Engineer']

In [3]:
label_encoder = LabelEncoder()

In [4]:
encoded_job_titles = label_encoder.fit_transform(job_titles)
print(encoded_job_titles)

[1 0 2 3 2 1]


In [5]:
# Define your categorical data
product_categories = ['Electronics', 'Clothing', 'Home Decor', 'Electronics', 'Books']

In [6]:
one_hot_encoder = OneHotEncoder(sparse=False)

In [7]:
product_categories = np.array(product_categories).reshape(-1, 1)

In [8]:
one_hot_encoded_data = one_hot_encoder.fit_transform(product_categories)
print(one_hot_encoded_data)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
