In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
raw_data = np.array([
 [3., -4., 5.],
 [5., 0., 1.],
 [6., 0., -2.]
])

In [3]:
min_max_scaler = preprocessing.MinMaxScaler()

In [4]:
scaled_min_max_data = min_max_scaler.fit_transform(raw_data)
print(scaled_min_max_data)

[[0.         0.         1.        ]
 [0.66666667 1.         0.42857143]
 [1.         1.         0.        ]]


In [5]:
std_scaler = preprocessing.StandardScaler().fit(raw_data)

In [6]:
std_data = std_scaler.transform(raw_data)

In [7]:
test_data = [[-3., 1., 2.]]
normalized_std_test_data = std_scaler.transform(test_data)
print(normalized_std_test_data)

[[-6.14700856  1.23743687  0.23249528]]


In [8]:
power_transformer = preprocessing.PowerTransformer(method='box-cox')

In [9]:
power_data = std_scaler.transform(raw_data)
print(power_data)

[[-1.33630621 -1.41421356  1.27872403]
 [ 0.26726124  0.70710678 -0.11624764]
 [ 1.06904497  0.70710678 -1.16247639]]
