In [1]:
import numpy as np

In [2]:
# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
 
print("Matrix A:")
print(A)
 
print("\nMatrix B:")
print(B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [3]:
# Matrix addition
C = A + B
 
print("\nMatrix C (Result of A + B):")
print(C)


Matrix C (Result of A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:
# Matrix subtraction
D = A - B
 
print("\nMatrix D (Result of A - B):")
print(D)


Matrix D (Result of A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [5]:
# Matrix multiplication
E = np.dot(A, B)
 
print("\nMatrix E (Result of A * B):")
print(E)


Matrix E (Result of A * B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
# Matrix transposition
F = np.transpose(A)
 
print("\nMatrix F (Transpose of A):")
print(F)


Matrix F (Transpose of A):
[[1 4 7]
 [2 5 8]
 [3 6 9]]
